### ISSUE TITLE
GISAID upload token

### ISSUE THREAD

**Issue by schultzm** [maximilianh/multiSub#1]
Hi Max, 

Regarding the upload token for GISAID.  In the manual for the CLI uploader there is a test token.

Cheers,

**Comment by maximilianh** [comment]
Thanks! I didn't see this! I'll try it.

**Comment by maximilianh** [comment]
This is fixed now and the test upload works. I'm curious: how did you find my tool? Do you upload SARS-CoV-2 sequences to GISAID?
